name: MarkTest
favicon: null
layout_spectrum: 0.11899153888225555
typography_spectrum: 0.2748590065166354
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.23725759610533714
  lightness: 0.9510809492785484
  saturation: 0.1977882629726082
  rhythmicContrast: 0.6132191007491201
purpose: []
