name: MarkTest
favicon: null
layout_spectrum: 0.11899153888225555
typography_spectrum: 0.2748590065166354
title: "This is Mark's Test Website"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a8d59a'
    - '#194b8d'
    - '#000000'
    - '#0000ff'
    - '#00ffff'
  brandStrength: 0.1875
  lightness: 0.875
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
